spring:
  application:
    name: department
  config:
    import: "optional:configserver:http://localhost:8088"


#server:
#  port: 8082

#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
